SET NAMES utf8 COLLATE utf8_unicode_ci;
DROP DATABASE IF EXISTS FILIPICH;
CREATE DATABASE FILIPICH
DEFAULT CHARACTER SET utf8;
USE FILIPICH;

CREATE TABLE Reviews
(
	ID INT(3) NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL,
    USERTEXT VARCHAR(500) NOT NULL,
    REVIEWDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IMGSRC VARCHAR(255),
	CONSTRAINT PK_Reviews
		PRIMARY KEY(ID)
);

INSERT INTO Reviews(USERNAME,IMGSRC)
VALUES('Марат','C:/img1.png');
SELECT*FROM Reviews;
